### ISSUE TITLE
Investigate Python 3.13 support

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/HYDROLIB-core#707]
**What is the need for this task.**
Python 3.13 was released on 1 October 2024, let's see if the testbanks pass.

**What is the task?**
- [x] add py3.13 to ci
- [x] release lxml upper bound since installation failed
- [x] installation failed on pandas error (which is not a dependency, but it comes from xarray). It fails because pandas 2.0.3 is being installed, while 2.2.3 is the first version that can be installed on python 3.13 >> add python-version-dependent pandas dependency to please poetry
- [x] upon installation of netCDF4: `ValueError: did not find HDF5 headers` >> https://github.com/Unidata/netcdf4-python/issues/1370
- [x] https://github.com/Deltares/HYDROLIB-core/issues/709
- [x] numpy<2 does not support python 3.13 yet, so this requirement has to be released: https://github.com/Deltares/HYDROLIB-core/issues/657
- [x] https://github.com/python/cpython/issues/125235 >> will be fixed in python 3.13.1 (December 2024)
- [x] if green, add py3.13 to pyproject.toml
